name:                shellter
version:             0.1.0.0
github:              "RiddleMan/shellter"
license:             BSD3
author:              "Artur Ptaszek"
maintainer:          "artur.ptaszek@gmail.com"
copyright:           "2021 Artur Ptaszek"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RiddleMan/shellter#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 0.58.1 && < 1.0
- mtl >= 2.2.2 && < 2.3.0
- containers >= 0.6.2.1 && < 0.7.0.0

library:
  source-dirs: src

executables:
  shellter-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shellter

tests:
  shellter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - shellter
